apiVersion: v1
kind: Service
metadata:
  name: client-api-dashboard
  labels:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: dashboard
spec:
  selector:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: dashboard
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-api-internal
  labels:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: internal
spec:
  selector:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: internal
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-api-external
  labels:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: external
spec:
  selector:
    app.kubernetes.io/name: client-api
    app.kubernetes.io/component: external
  ports:
  - name: http
    protocol: TCP
    port: 80
