apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app.kubernetes.io/name: website
spec:
  selector:
    app.kubernetes.io/name: website
  ports:
    - name: express-node
      protocol: TCP
      port: 3000
    - name: nginx
      protocol: TCP
      port: 80
    - name: prometheus
      protocol: TCP
      port: 9144
