apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
namePrefix: prod-
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: website
    newName: artifactory.service.canary.sh:5000/cnry/website
resources:
  - ../base
  - ingress.yaml
