apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
namePrefix: dev-
patchesStrategicMerge:
  - deployment.yaml
images:
- name: website
  newName: artifactory.service.canary.sh:5000/canary-docker/website:dev-11
resources:
- ../base
- ingress.yaml
