apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client-api
namePrefix: stage-
patchesStrategicMerge:
  - deployment.yaml
images:
- name: client-api
  newName: artifactory.service.canary.sh:5000/cnry/client-api
resources:
- ../base
- ingress.yaml
