apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce-panel
  labels:
    app.kubernetes.io/name: ce-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ce-panel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ce-panel
      annotations:
        cnry.kubernetes.io/tattler-enabled: "true"
    spec:
      containers:
        - name: ce-panel
          image: ce-panel
          imagePullPolicy: Always
          env:
            - name: USE_TATTLER
              value: "1"
          ports:
            - name: node
              containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /usr/src/app/settings/
              name: tattler-vol
              subPath: ce-panel
      initContainers:
        - image: artifactory.service.canary.sh:5000/canary-docker/tattler-agent:dev-latest
          name: tattler-agent
          env:
            - name: TATTLER_ARGS
              value: --config /src/config/ce-panel.js.hcl --once --vault-addr http://k8s-active-vault.cluster-service-consul.svc.cluster.local --consul-addr k8s-consul.cluster-service-consul.svc.cluster.local -vault-renew-token=false
          volumeMounts:
            - mountPath: /secrets
              name: tattler-vol
      volumes:
        - emptyDir: {}
          name: tattler-vol
