apiVersion: v1
kind: Service
metadata:
  name: ce-panel
  labels:
    app.kubernetes.io/name: ce-panel
spec:
  selector:
    app.kubernetes.io/name: ce-panel
  ports:
    - name: node
      protocol: TCP
      port: 3000

